### PR TITLE
Add initial support for i.MX8

### PR DESCRIPTION
**Pull request by dianacretu**

### CODE REVIEW

**Comment by dbaluta** [comment]
@dianacretu lets also try to rebase our changes on top of 4.2 branch as @lgirdwood mentioned in a previous comment.

**Comment by lgirdwood** [comment]
@dianacretu yes, please do on top of 4.2. This is our path to upstreaming as it's latest release. Once merged then @xiulipan can update travis to use lates qemu and include imx in boot test.

**Comment by xiulipan** [comment]
@lgirdwood @dbaluta Got that, please ping me when this support is done, I will try to check the qemu update patch first.
PS: @lgirdwood What branch should we use now for QEMU? Do I need to change the Dockerfile for this.

**Comment by dbaluta** [comment]
@lgirdwood @xiulipan closing this now, as we moved to branch 4.2 here -> https://github.com/thesofproject/qemu/pull/31

**Comment by dianacretu** [comment]
@lgirdwood should we close this PR and only follow changes for qemu 4.2?

**Comment by lgirdwood** [comment]
@dianacretu yes

**Pull request closed without merging**
