### PR TITLE
Add support for i.MX8

### PR DESCRIPTION
**Pull request by dianacretu**
This is a rebase on branch sof v4.2. For now, it successfully boots image for i.MX8. Most of the devices implementation is dummy (IRQ Steer, MU).

### CODE REVIEW

**Comment by dbaluta** [comment]
@dianacretu thanks! Will do a complete review later.

@lgirdwood should we go with this branch from now? That means that our sof-stable should point to 4.2? And we discard the changes we've done on the previous sof-stable.

**Comment by lgirdwood** [comment]
@dbaluta yes - @xiulipan when would be a good time to transition CI ?

**Review by lgirdwood — APPROVED** [review]

**Comment by xiulipan** [comment]
@lgirdwood Anytime is OK, some configure is still need manually involved and test. If the code is ready I can start to send PR for the scripts and start to test locally first

**Review by dbaluta — APPROVED** [review]

**Comment by dbaluta** [comment]
@xiulipan code looks good to me. It is enough to have the boot test working. We will add device driver implementation and other stuff later.

**Review by xiulipan — APPROVED** [review]
@lgirdwood Test with Intel fws with this PR based on sof-v4.2 branch. Good to go. Please inform me to update the docker image when the sof-stable branch is ready.

**Comment by dbaluta** [comment]
@lgirdwood @xiulipan This means we need to merge this PR and then update docker image.

**Comment by lgirdwood** [comment]
@xiulipan @dbaluta merged.

**Comment by xiulipan** [comment]
@lgirdwood Will we change the sof-stable branch or we should use sof-v4.2 instead?

**Comment by xiulipan** [comment]
@lgirdwood I have updated the docker image from sof-v4.2 for tmp solution as imx8 check is added in Travis.

**Comment by lgirdwood** [comment]
@xiulipan thanks, sof-v4.2 is now correct branch. Let me update this as default on GH too.

**Pull request merged**
